In [ ]:
#This Notebook contains Resnet34 model with batch size 32 for 100 epochs.
#Results are added here for ease of reference
#acc: 0.8038768529076397
#f1: 0.7844764529263898
#cm: [[220   5  11]
# [  4 371  42]
# [  7 103 114]]

In [1]:
import sys
sys.path.append('../../src/')

In [2]:
%load_ext autoreload
%autoreload 2

from train import train_model
from model import initialize_model
from utils import set_requires_grad, save_model
from data import load_data
from plotting import plot_data_loader
from eval import eval_model

In [3]:
import os
import copy
import time
import random
import pickle

import numpy as np
import pandas as pd
from PIL import Image
from pathlib import Path
from tqdm import tqdm

from sklearn.metrics import f1_score, confusion_matrix
from numpy.random import shuffle
import matplotlib.pyplot as plt

import torch
import torchvision
from torchvision.io import read_image
import torchvision.transforms as T
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, models, transforms
import torch.autograd.profiler as tprofiler
import torch.utils.data as td

plt.rcParams["savefig.bbox"] = 'tight'

In [4]:
seed = 42

random.seed(seed)

# pytorch RNGs
torch.manual_seed(seed)
torch.backends.cudnn.deterministic = True
if torch.cuda.is_available(): torch.cuda.manual_seed_all(seed)

# numpy RNG
np.random.seed(seed)

In [5]:
data_dir = "../../data"
images_dir = "../../data/chest_xray"

In [6]:
# Get best num_workers
# for i in range(97):
#     start = time.time()
#     data_loader = load_data(images_dir,
#                                                                    batch_size = 96, 
#                                                                    input_size = 299, 
#                                                                    norm_arr = ([0.485, 0.456, 0.406], [0.229, 0.224, 0.225]),
#                                                                    num_workers = i)
#     iter(data_loader['train']).next()[0].shape
#     print(f"{i}: {time.time()-start}")

In [7]:
# Models options: resnet50, resnet34, inceptionv3, vgg16, mobile_net_v3_large, efficient_net_b1, efficient_net_b0.
model_name = "resnet34"

# Number of classes.
num_classes = 3

# Batch Size.
batch_size = 32

# Epochs to train for.
num_epochs = 100

# Number of workers for data loader.
num_workers = 0

# Imagenet norm array passed as default value.
# norm_arr=([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
# Chest x-ray8 training dataset metrics 
# norm_arr=([0.4951, 0.4951, 0.4951], [0.2896, 0.2896, 0.2896])
# Pneumonia dataset metrics
norm_arr=([0.4810, 0.4810, 0.4810], [0.2373, 0.2373, 0.2373])

# Feature extract flag: False - Tune the whole model,
#                       True - Update only the reshaped layer parameters.
feature_extract = False

# Use pretrained flag: None - Use random weights
#                      String - Use pretrained weights given by String
use_pretrained = None

# Initialize the model for this run.
model_pyt, input_size = initialize_model(model_name, num_classes, feature_extract, use_pretrained=use_pretrained)

# lr start and end points for training.
lr_start = 0.01
lr_end = 0.001

# How many epochs to restart.
iter_restart = 10

# Multiplication factor after restart.
mul_restart = 1

# Print the model we just instantiated
#print(model_ft)

In [8]:
data_loaders = load_data(images_dir,
                         batch_size = batch_size, 
                         input_size = (input_size, input_size), 
                         norm_arr = norm_arr,
                         num_workers = num_workers)

plot_data_loader(data_loader['train'], (2,2))

plot_data_loader(data_loader['test'], (2,2))

plot_data_loader(data_loader['val'], (2,2))

In [9]:
# Check if GPU is available.
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
print(device)

# Send model to GPU
model_pyt = model_pyt.to(device)

# Find parameters to be updated in this run.
# parameters with requires_grad = True.
params_to_update = model_pyt.parameters()
print("Params to learn:")
if feature_extract:
    params_to_update = []
    for name,param in model_pyt.named_parameters():
        if param.requires_grad == True:
            params_to_update.append(param)
            print("\t",name)
else:
    for name,param in model_pyt.named_parameters():
        if param.requires_grad == True:
            print("\t",name)

cuda:0
Params to learn:
	 conv1.weight
	 bn1.weight
	 bn1.bias
	 layer1.0.conv1.weight
	 layer1.0.bn1.weight
	 layer1.0.bn1.bias
	 layer1.0.conv2.weight
	 layer1.0.bn2.weight
	 layer1.0.bn2.bias
	 layer1.1.conv1.weight
	 layer1.1.bn1.weight
	 layer1.1.bn1.bias
	 layer1.1.conv2.weight
	 layer1.1.bn2.weight
	 layer1.1.bn2.bias
	 layer1.2.conv1.weight
	 layer1.2.bn1.weight
	 layer1.2.bn1.bias
	 layer1.2.conv2.weight
	 layer1.2.bn2.weight
	 layer1.2.bn2.bias
	 layer2.0.conv1.weight
	 layer2.0.bn1.weight
	 layer2.0.bn1.bias
	 layer2.0.conv2.weight
	 layer2.0.bn2.weight
	 layer2.0.bn2.bias
	 layer2.0.downsample.0.weight
	 layer2.0.downsample.1.weight
	 layer2.0.downsample.1.bias
	 layer2.1.conv1.weight
	 layer2.1.bn1.weight
	 layer2.1.bn1.bias
	 layer2.1.conv2.weight
	 layer2.1.bn2.weight
	 layer2.1.bn2.bias
	 layer2.2.conv1.weight
	 layer2.2.bn1.weight
	 layer2.2.bn1.bias
	 layer2.2.conv2.weight
	 layer2.2.bn2.weight
	 layer2.2.bn2.bias
	 layer2.3.conv1.weight
	 layer2.3.bn1.weight
	 layer2

In [11]:
# 17 min 1 epoch - 128 batch size - inception
# Efficientnet b0 - batch 96 - epoch 50 - num_workers 2 - flip, auto cont, sharp - 

In [10]:
# Observe that all parameters are being optimized
optimizer = optim.Adam(params_to_update, lr=lr_start)

# Learning rate scheduler.
# Learning rate scheduler.
scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=num_epochs, 
                                                           eta_min=lr_end, last_epoch=-1)
# Setup the loss fxn
criterion = nn.CrossEntropyLoss()

# Train and evaluate
model_pyt, prof, val_history, train_history = train_model(device, model_pyt, data_loaders, 
                                                            optimizer, scheduler,
                                                            criterion, 
                                                            num_epochs=num_epochs,
                                                            num_classes=num_classes,
                                                            is_inception=(model_name=="inceptionv3"),
                                                            profiler=False)

Epoch 1/100
----------
Epoch [1/100], Step [100/129], Loss: 0.6297, Accuracy: 24.00%
train Loss: 1.0072 Acc: 0.5914
val Loss: 0.7311 Acc: 0.6944

Epoch 2/100
----------
Epoch [2/100], Step [100/129], Loss: 0.8477, Accuracy: 20.00%
train Loss: 0.7025 Acc: 0.6970
val Loss: 0.9003 Acc: 0.6192

Epoch 3/100
----------
Epoch [3/100], Step [100/129], Loss: 0.6061, Accuracy: 22.00%
train Loss: 0.6282 Acc: 0.7325
val Loss: 0.7574 Acc: 0.6454

Epoch 4/100
----------
Epoch [4/100], Step [100/129], Loss: 0.6759, Accuracy: 24.00%
train Loss: 0.6066 Acc: 0.7400
val Loss: 0.6396 Acc: 0.7412

Epoch 5/100
----------
Epoch [5/100], Step [100/129], Loss: 0.4268, Accuracy: 26.00%
train Loss: 0.5676 Acc: 0.7626
val Loss: 0.9837 Acc: 0.5610

Epoch 6/100
----------
Epoch [6/100], Step [100/129], Loss: 0.7382, Accuracy: 18.00%
train Loss: 0.5688 Acc: 0.7656
val Loss: 0.6805 Acc: 0.7081

Epoch 7/100
----------
Epoch [7/100], Step [100/129], Loss: 0.7036, Accuracy: 23.00%
train Loss: 0.5572 Acc: 0.7709
val Loss

In [11]:
dataset_name = 'pneumonia'

In [12]:
save_model(model_pyt, '../../models/', 
           f'{model_name}_{dataset_name}_{num_epochs}_{batch_size}_{lr_start}_{lr_end}_model_weights.pth')

True

In [13]:
eval_metrics = eval_model(device=device, model=model_pyt, test_loader=data_loaders['test'], is_inception=(model_name=="inceptionv3"))

In [14]:
val_history

{'acc': [tensor(0.6944, device='cuda:0', dtype=torch.float64),
  tensor(0.6192, device='cuda:0', dtype=torch.float64),
  tensor(0.6454, device='cuda:0', dtype=torch.float64),
  tensor(0.7412, device='cuda:0', dtype=torch.float64),
  tensor(0.5610, device='cuda:0', dtype=torch.float64),
  tensor(0.7081, device='cuda:0', dtype=torch.float64),
  tensor(0.7195, device='cuda:0', dtype=torch.float64),
  tensor(0.7526, device='cuda:0', dtype=torch.float64),
  tensor(0.7548, device='cuda:0', dtype=torch.float64),
  tensor(0.7434, device='cuda:0', dtype=torch.float64),
  tensor(0.7651, device='cuda:0', dtype=torch.float64),
  tensor(0.7788, device='cuda:0', dtype=torch.float64),
  tensor(0.7742, device='cuda:0', dtype=torch.float64),
  tensor(0.7605, device='cuda:0', dtype=torch.float64),
  tensor(0.7605, device='cuda:0', dtype=torch.float64),
  tensor(0.7834, device='cuda:0', dtype=torch.float64),
  tensor(0.7662, device='cuda:0', dtype=torch.float64),
  tensor(0.7811, device='cuda:0', dtype=t

In [15]:
train_history

{'acc': [0.5914396887159533,
  0.6969844357976653,
  0.7324902723735409,
  0.7400291828793775,
  0.7626459143968871,
  0.7655642023346304,
  0.7709143968871596,
  0.7816147859922179,
  0.7821011673151751,
  0.7876945525291829,
  0.7867217898832685,
  0.7932879377431906,
  0.7932879377431906,
  0.8013132295719845,
  0.7957198443579767,
  0.8025291828793775,
  0.8047178988326849,
  0.8044747081712063,
  0.8090953307392996,
  0.8105544747081712,
  0.816147859922179,
  0.8224708171206225,
  0.8217412451361867,
  0.8292801556420234,
  0.8232003891050583,
  0.828307392996109,
  0.8373054474708171,
  0.8370622568093385,
  0.8336575875486382,
  0.8504377431906615,
  0.8448443579766537,
  0.8545719844357976,
  0.853112840466926,
  0.8591926070038911,
  0.867704280155642,
  0.8754863813229572,
  0.882295719844358,
  0.8839980544747081,
  0.8988326848249028,
  0.9061284046692607,
  0.9233949416342413,
  0.9229085603112841,
  0.9392023346303502,
  0.9377431906614786,
  0.9484435797665369,
  0.9550

In [16]:
for i, v in eval_metrics.items():
    print(f"{i}: {v}")

acc: 0.8038768529076397
f1: 0.7844764529263898
cm: [[220   5  11]
 [  4 371  42]
 [  7 103 114]]
outputs: [0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0
 2 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 2
 0 0 1 0 0 0 0 0 0 2 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 1 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 2 1 1 1 2 2 1 1 1 2 1 1 2 1 1 1 1 1 1 1 1
 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 0 2 2 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1 2 1
 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 2 1 1 1 1 2 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1
 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1 1 2 1 1 

In [17]:
with open(f'../../models/val_history_{model_name}_{dataset_name}_{num_epochs}_{batch_size}_{lr_start}_{lr_end}_.pickle', 'wb') as handle:
    pickle.dump(val_history, handle, protocol=pickle.HIGHEST_PROTOCOL)
with open(f'../../models/train_history_{model_name}_{dataset_name}_{num_epochs}_{batch_size}_{lr_start}_{lr_end}_.pickle', 'wb') as handle:
    pickle.dump(train_history, handle, protocol=pickle.HIGHEST_PROTOCOL)
with open(f'../../models/eval_metrics_{model_name}_{dataset_name}_{num_epochs}_{batch_size}_{lr_start}_{lr_end}_.pickle', 'wb') as handle:
    pickle.dump(eval_metrics, handle, protocol=pickle.HIGHEST_PROTOCOL)

#with open('filename.pickle', 'rb') as handle:
#    b = pickle.load(handle)

In [ ]:
#print(prof.key_averages(group_by_stack_n=5).table(sort_by='self_cpu_time_total', row_limit=50))

In [9]:
# Plot the training curves of validation accuracy vs. number
#  of training epochs for the transfer learning method and
#  the model trained from scratch
# vhist = []
# vhist = [h.cpu().numpy() for h in val_acc_history]
# thist = []
# thist = [h.cpu().numpy() for h in train_acc_history]

# plt.title("Accuracy vs. Number of Training Epochs")
# plt.xlabel("Training Epochs")
# plt.ylabel("Accuracy")
# #plt.plot(range(1,num_epochs+1),ohist,label="Pretrained")
# plt.plot(range(1,num_epochs+1),vhist,label="Validation")
# plt.plot(range(1,num_epochs+1),thist,label="Training")
# plt.ylim((0,1.))
# plt.xticks(np.arange(1, num_epochs+1, 1.0))
# plt.legend()
# plt.show()

In [8]:
# Plot the training curves of validation accuracy vs. number
#  of training epochs for the transfer learning method and
#  the model trained from scratch
# vhist = []
# vhist = [h for h in val_loss_history]
# thist = []
# thist = [h for h in train_loss_history]

# plt.title("Loss vs. Number of Training Epochs")
# plt.xlabel("Training Epochs")
# plt.ylabel("Loss")
# #plt.plot(range(1,num_epochs+1),ohist,label="Pretrained")
# plt.plot(range(1,num_epochs+1),vhist,label="Validation")
# plt.plot(range(1,num_epochs+1),thist,label="Training")
# plt.ylim((0,1.))
# plt.xticks(np.arange(1, num_epochs+1, 1.0))
# plt.legend()
# plt.show()